### ISSUE TITLE
devtools::install_github("mcjmigdal/xcoredata@r4_1") doesn't work

### ISSUE THREAD

**Issue by bkaczkowski** [mcjmigdal/xcoredata#2]
Hi @mcjmigdal 
The following error occured

installing *source* package ‘xcoredata’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘utils’ 4.1.2 is already loaded, but >= 4.2.0 is required
Calls: <Anonymous> ... namespaceImportFrom -> asNamespace -> loadNamespace
Execution halted
ERROR: lazy loading failed for package ‘xcoredata’
* removing ‘/Library/Frameworks/R.framework/Versions/4.1/Resources/library/xcoredata’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/lk/gxlfh64d455_3pxgr7g4kj840000gn/T//RtmpNNB1uq/file652b1442ac9b/xcoredata_0.99.2.tar.gz’ had non-zero exit status

**Comment by mcjmigdal** [comment]
should be solved a16a56ace6c4d58ef29900e85993c92c5b96f1fb
